---
title: "Simple document"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)

```

Let's import the `FAS_litters.csv` csv.

```{r}
litters_df = 
  read_csv("Data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)

# Cleaning the names using the janitor package
```

Import the same dataset using the absolute path
```{r}

# Absolute path
litters_df_abs = 
  read_csv("/Users/BettyWu/Desktop/Columbia/Intro to DS/data_wrangling_i/Data/FAS_litters.csv")

litters_df_abs =
  janitor::clean_names(litters_df_abs)

```

Import pups dataset
```{r}
pups_df = 
  read_csv("Data/FAS_pups.csv")

pups_df =
  janitor::clean_names(pups_df)
```

## Look at data

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

you can use `view`
```{r, eval = FALSE}
view(litters_df)
```

Look at a data summary
```{r}
str(litters_df)
skimr::skim(litters_df)
```

## Options in read_*

```{r}
litters_df = 
  read_csv("Data/FAS_litters.csv",
           skip = 10, col_names = FALSE)
```

Look at NA values

```{r}
litters_df =
  read_csv("Data/FAS_litters.csv", na = c("NA", 19, "."))

```

Column types

```{r}
litters_df = 
  read_csv("Data/FAS_litters.csv",
           col_types = cols(`GD0 Weight` = col_character()))
```

## Other file types

import a xlsx file first

```{r}
mlb_df = 
  read_excel("Data/mlb11.xlsx")

```

Import a SAS file
```{r}
pulse_df = 
  read_sas("Data/public_pulse_data.sas7bdat")

```

## Base R ...

don't do this
```{r}
#litter_df = read.csv("Data/FAS_litter.csv")
```

```{r}
litters_df_cleaned = 
  read_csv("Data/FAS_litters.csv")

litters_df_cleaned =
  janitor::clean_names(litters_df_cleaned)

write_csv(litters_df_cleaned, "Data/litters_cleaned.csv")

```
